#!/usr/bin/env python3
"""Phase C end-to-end test — nous replay CLI subcommands.

Depends on: /tmp/nous_replay_e2e.jsonl (generated by tests/test_replay_e2e.py
Phase B run). If missing, this test auto-runs Phase B first.

Covers:
  * replay <log>               → summary (exit 0)
  * replay <log> --verify      → intact (exit 0)
  * replay <log> --verify      → broken (exit 2) on tampered log
  * replay <log> --diff <log>  → identical (exit 0)
  * replay A --diff B          → divergent (exit 3)
  * replay <log> --mutate src  → equivalent (exit 0)
  * replay <log> --mutate src  → divergent (exit 4)
  * replay <missing>           → I/O error (exit 1)
"""
# __phase_c_e2e_v1__
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path("/opt/aetherlang_agents/nous")
CLI = ROOT / "cli.py"
BASELINE_LOG = Path("/tmp/nous_replay_e2e.jsonl")
TAMPERED_LOG = Path("/tmp/nous_phase_c_tampered.jsonl")
SECOND_LOG = Path("/tmp/nous_phase_c_second.jsonl")
DIVERGENT_SRC = Path("/tmp/nous_phase_c_divergent.nous")
EQUIV_SRC = ROOT / "tests" / "test_replay_e2e.nous"
PHASE_B = ROOT / "tests" / "test_replay_e2e.py"

GREEN = "\033[32m"
RED = "\033[31m"
YELLOW = "\033[33m"
RESET = "\033[0m"


def green(msg: str) -> None:
    print(f"{GREEN}  ✓ {msg}{RESET}")


def red(msg: str) -> None:
    print(f"{RED}  ✗ {msg}{RESET}")


def step(msg: str) -> None:
    print(f"{YELLOW}[STEP] {msg}{RESET}")


def run_cli(*args: str) -> tuple[int, str, str]:
    """Run `python3 cli.py replay <args>` and capture exit/out/err."""
    proc = subprocess.run(
        [sys.executable, str(CLI), "replay", *args],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout, proc.stderr


def ensure_baseline() -> None:
    if BASELINE_LOG.exists() and BASELINE_LOG.stat().st_size > 0:
        return
    step("baseline log missing — running Phase B E2E first")
    proc = subprocess.run(
        [sys.executable, str(PHASE_B)],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"Phase B test failed: {proc.stderr}")


def make_tampered() -> None:
    shutil.copy2(BASELINE_LOG, TAMPERED_LOG)
    lines = TAMPERED_LOG.read_text(encoding="utf-8").splitlines()
    if len(lines) < 6:
        raise RuntimeError("baseline log too short to tamper")
    d = json.loads(lines[5])
    d.setdefault("data", {})["tampered"] = True
    lines[5] = json.dumps(d, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    TAMPERED_LOG.write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_second_log_identical() -> None:
    shutil.copy2(BASELINE_LOG, SECOND_LOG)


def make_divergent_source() -> None:
    DIVERGENT_SRC.write_text('''world ReplayE2E {
    law cost_ceiling = $1.00 per cycle
    heartbeat = 10s
    replay {
        enabled: true
        mode: record
        store: jsonl
        path: "/tmp/nous_replay_e2e.jsonl"
        fsync: every_event
        seed_base: 42
        capture: [sense, memory, clock, random]
    }
}

sense counter_tick {
    description: "tick"
    http_get: "http://unused.local/tick"
    timeout: 5
    returns: json
    cache_ttl: 0
}

sense extra_sense {
    description: "divergence"
    http_get: "http://unused.local/extra"
    timeout: 5
    returns: json
    cache_ttl: 0
}

soul Ticker {
    mind: deepseek-chat @ Tier1
    senses: [counter_tick, extra_sense]
    memory {
        ticks: int = 0
        last_value: int = 0
    }
    instinct {
        let v = sense counter_tick()
        let x = sense extra_sense()
        remember ticks = ticks + 1
        remember last_value = ticks
    }
    heal {
        on api_error => retry(3, api_error)
    }
}
''', encoding="utf-8")


def assert_exit(label: str, got: int, expected: int, stdout: str, stderr: str) -> None:
    if got != expected:
        red(f"{label}: expected exit={expected}, got {got}")
        print(f"    stdout: {stdout[:200]}")
        print(f"    stderr: {stderr[:200]}")
        raise AssertionError(f"{label} exit code mismatch")
    green(f"{label} → exit={got}")


def main() -> int:
    ensure_baseline()

    step("setup fixtures")
    make_tampered()
    make_second_log_identical()
    make_divergent_source()
    green("fixtures prepared")

    try:
        # 1. summary (default)
        step("summary (default)")
        rc, out, err = run_cli(str(BASELINE_LOG))
        assert_exit("summary", rc, 0, out, err)
        assert "total events:" in out, "summary output missing totals"
        assert "chain status:   intact" in out, "summary should show intact chain"
        green("summary prints totals + chain status")

        # 2. summary --json
        step("summary --json")
        rc, out, err = run_cli(str(BASELINE_LOG), "--json")
        assert_exit("summary --json", rc, 0, out, err)
        parsed = json.loads(out)
        assert parsed["chain_status"] == "intact"
        assert parsed["total_events"] > 0
        green("json summary structurally valid")

        # 3. verify intact
        step("verify intact log")
        rc, out, err = run_cli(str(BASELINE_LOG), "--verify")
        assert_exit("verify intact", rc, 0, out, err)

        # 4. verify broken
        step("verify tampered log")
        rc, out, err = run_cli(str(TAMPERED_LOG), "--verify")
        assert_exit("verify tampered", rc, 2, out, err)
        assert "FAIL" in out
        green("verify catches tampering")

        # 5. verify --json on broken
        step("verify tampered --json")
        rc, out, err = run_cli(str(TAMPERED_LOG), "--verify", "--json")
        assert_exit("verify tampered --json", rc, 2, out, err)
        parsed = json.loads(out)
        assert parsed["status"] == "broken"
        assert isinstance(parsed["first_bad_seq"], int)
        green("json reports first_bad_seq")

        # 6. diff identical
        step("diff identical logs")
        rc, out, err = run_cli(str(BASELINE_LOG), "--diff", str(SECOND_LOG))
        assert_exit("diff identical", rc, 0, out, err)
        assert "IDENTICAL" in out

        # 7. diff divergent
        step("diff vs tampered")
        rc, out, err = run_cli(str(BASELINE_LOG), "--diff", str(TAMPERED_LOG), "--deep")
        assert_exit("diff divergent", rc, 3, out, err)
        assert "divergences" in out

        # 8. mutate equivalent
        step("mutate with original source (expect EQUIVALENT)")
        rc, out, err = run_cli(str(BASELINE_LOG), "--mutate", str(EQUIV_SRC))
        assert_exit("mutate equivalent", rc, 0, out, err)
        assert "EQUIVALENT" in out

        # 9. mutate divergent
        step("mutate with divergent source (expect DIVERGENT)")
        rc, out, err = run_cli(str(BASELINE_LOG), "--mutate", str(DIVERGENT_SRC))
        assert_exit("mutate divergent", rc, 4, out, err)
        assert "DIVERGENT" in out

        # 10. missing file
        step("missing file")
        rc, out, err = run_cli("/tmp/does_not_exist_xyz.jsonl", "--verify")
        assert_exit("missing file", rc, 1, out, err)

        print()
        print(f"{GREEN}================================================{RESET}")
        print(f"{GREEN}PHASE C E2E TEST — ALL GREEN{RESET}")
        print(f"{GREEN}================================================{RESET}")
        return 0
    finally:
        for p in (TAMPERED_LOG, SECOND_LOG, DIVERGENT_SRC):
            try:
                p.unlink()
            except FileNotFoundError:
                pass


if __name__ == "__main__":
    sys.exit(main())
