from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT: Path = Path(__file__).resolve().parent.parent
_WS: re.Pattern[str] = re.compile(r"\s+")

# __s377_reserved_verb_copy_v1__
# D376-8: every OVER and SCOPE id corrected by patch A, named by its id in
# S376_PROVE_CLASSIFICATION.tsv. Whitespace is normalized, so a phrase may
# span a wrapped line.

OVERCLAIMS: tuple[tuple[str, str, str], ...] = (
    ('o0062', 'README.md', 'prove a signed execution trace stayed inside'),
    ('o0196', 'docs/ANNEX_IV_MAPPING.md', 'certificate proves the trace conforms'),
    ('o0200', 'docs/ANNEX_IV_MAPPING.md', 'embedded in the manifest proves the artifact existed'),
    ('o0204', 'docs/ANNEX_IV_MAPPING.md', '`verify_annex_iv_map.py` proves presence, authenticity,'),
    ('o0209', 'docs/ATTESTATION_RECEIPT.md', 'what tee_attested proves, and what it does not'),
    ('o0210', 'docs/ATTESTATION_RECEIPT.md', 'PROVES: the per-event token counts'),
    ('o0213', 'docs/ATTESTATION_RECEIPT.md', 'A TEE receipt proves provenance'),
    ('o0215', 'docs/ATTESTATION_RECEIPT.md', 'S146 proves the mechanism'),
    ('o0289+o0290#1', 'docs/COST_VERIFICATION_GUIDE.md', 'NOUS proves it through math'),
    ('o0289+o0290#2', 'docs/COST_VERIFICATION_GUIDE.md', 'and have a solver prove the ceiling can never be exceeded'),
    ('o0292#1', 'docs/COST_VERIFICATION_GUIDE.md', 'to declare and prove their performance metrics'),
    ('o0292#2', 'docs/COST_VERIFICATION_GUIDE.md', 'NOUS is the first language where this'),
    ('o0356', 'docs/EU_AI_ACT_COMPLIANCE.md', 'Constraints are mathematically proven before deployment'),
    ('o0363', 'docs/GATED_ACTIONS.md', 'obligation #5 (authorization) proves that every trace'),
    ('o0364', 'docs/GATED_ACTIONS.md', '## What this proves, and what it does not'),
    ('o0365', 'docs/GATED_ACTIONS.md', '**Proves (completeness of the gated set):**'),
    ('o0367', 'docs/GATED_ACTIONS.md', 'Obligation #5 proves that SOME key'),
    ('o0500', 'docs/RUNTIME_CONFORMANCE.md', 'the program **cannot** exceed its declared cost envelope'),
    ('o0501', 'docs/RUNTIME_CONFORMANCE.md', 'rather than counted as proven'),
    ('o0502', 'docs/RUNTIME_CONFORMANCE.md', 'The offline verifier proves the signed verdict'),
    ('o0503', 'docs/RUNTIME_CONFORMANCE.md', 'The certificate proves the **trace** conforms'),
    ('o0504', 'docs/RUNTIME_CONFORMANCE.md', '**What obligation #5 now proves**'),
    ('o0506', 'docs/RUNTIME_CONFORMANCE.md', 'The verifier proves that SOME key'),
    ('o0526', 'docs/SEQUENCE_LAWS.md', 'the DICE proves a game was played'),
    ('o0527', 'docs/SEQUENCE_LAWS.md', '(no run exceeds the cap)'),
    ('o0530', 'docs/SEQUENCE_LAWS.md', 'The certificate proves the trace conforms'),
    ('o0575', 'docs/VERIFY_DOSSIER.md', '| What it proves |'),
    ('o0581', 'docs/WITNESSED_RUN_EVIDENCE.md', 'The compiled path proves a cost ENVELOPE'),
    ('o0582', 'docs/WITNESSED_RUN_EVIDENCE.md', 'PROVEN: obligation #4 recomputes'),
    ('o0583', 'docs/WITNESSED_RUN_EVIDENCE.md', 'the signature proves the ISSUER did not tamper'),
    ('o0805', 'trace/SPEC.md', 'The Verifier proves *consistency of record and verdict*'),
    ('o1116', 'website/index.html', 'hold across every path your AI agents could take'),
    ('o1118', 'website/index.html', 'The system proves the declared rules hold across every path the agent could take'),
    ('o1121', 'website/index.html', 'NOUS builds a mathematical region that proves the declared rules hold across every path the agent could take'),
    ('o1123', 'website/index.html', 'the literature talks about: a mathematical region that proves the declared rules hold across every path the agent could take'),
    ('o1130', 'website/index.html', '>A mathematical region that proves the declared rules hold across every path the agent could take.<'),
    ('o1138', 'website/index.html', 'A formal envelope that proves the declared rules hold across every path.'),
    ('o1143', 'website/index.html', 'NOUS proves they hold, and records every decision'),
    ('o1147', 'website/lending.html', 'NOUS proves the policy, and evidences'),
    ('o1150', 'website/lending.html', '<h3>What this proves</h3>'),
    ('D376-7-lending-trust', 'website/lending.html', 'offline, with zero trust in any party'),
    ('o1154', 'website/runtime.html', 'the behaviour NOUS proves'),
    ('o0881', 'website/blog/index.html', '<h2 class="post-title">v5.66.0 &mdash; The Cost Cap Reaches the Dossier, On a Path That Proves Itself</h2>'),
    ('o0937', 'website/blog/index.html', '<h1>v5.66.0 &mdash; The Cost Cap Reaches the Dossier, On a Path That Proves Itself</h1>'),
    ('o0938', 'website/blog/index.html', '<strong>The path that proves itself.</strong>'),
    ('o0939', 'website/blog/index.html', 'The pipeline now proves its own provenance'),
    ('o0887', 'website/blog/index.html', 'leg proving the log-anchored digest'),
    ('o0899', 'website/blog/index.html', 'Mechanism and conformance proven;'),
    ('o0900', 'website/blog/index.html', 'it proves the issuer did not tamper with the relayed usage'),
    ('o0903', 'website/blog/index.html', 'It proves presence and indexing'),
    ('o0915', 'website/blog/index.html', 'The envelope-binding chain proved an unbroken lineage'),
    ('o0919', 'website/blog/index.html', 'A certificate proves one build stayed in its envelope.'),
    ('o0921', 'website/blog/index.html', 'laws separately from proven ones'),
    ('o0952', 'website/blog/index.html', 'The digest Root 2 proves inclusion of'),
    ('o0962', 'website/blog/index.html', 'the conformance certificate proves the run stayed inside the envelope'),
    ('o0974', 'website/blog/index.html', 'the signature proves authenticity'),
    ('o0982', 'website/blog/index.html', 'which prove each decision verb is cryptographically bound'),
    ('o0991', 'website/blog/index.html', 'transparency log, proven by a hashedrekord inclusion proof'),
    ('o0994', 'website/blog/index.html', 'A NOUS dossier already proves what it claims offline'),
    ('o0997', 'website/blog/index.html', 'v5.45.0 proves the mechanism'),
    ('o0998+o0999', 'website/blog/index.html', 'asserts (proven). The trace faithfully records what the runtime saw (assumed, but the signature proves the issuer'),
    ('o1000', 'website/blog/index.html', 'A receipt thus proves provenance'),
    ('o1001+o1002', 'website/blog/index.html', 'asserts (proven), the trace faithfully records what the runtime saw (assumed, but the signature proves the issuer'),
    ('o1005', 'website/blog/index.html', 'that the system&rsquo;s cost stays inside a declared SMT envelope'),
    ('o1006', 'website/blog/index.html', 'This proves presence, authenticity, and indexing'),
    ('o1031+o1032', 'website/blog/index.html', 'A conformance certificate proves one build stayed inside its declared envelope. The v5.29.0 envelope-binding chain proved something'),
    ('o1039', 'website/blog/index.html', 'NOUS proves what it can sign'),
    ('o1045', 'website/blog/index.html', 'a previously proven recovery'),
    ('o1046', 'website/blog/index.html', 'to prove the run consulted exactly the memory state'),
    ('o1047', 'website/blog/index.html', 'a third party can prove a run trace existed'),
    ('o1049', 'website/blog/index.html', 'and prove it conforms.'),
    ('o1050', 'website/blog/index.html', 'separately from genuinely proven ones'),
    ('o1053', 'website/blog/index.html', 'the certificate proves the <em>trace</em> conforms'),
    ('o1054', 'website/blog/index.html', '<h2>What it proves, and what it does not</h2>'),
    ('o1063', 'website/blog/index.html', '(no execution path exceeds the cap)'),
    ('o1065', 'website/blog/index.html', 'Z3 round-trip on EUR proves the architecture'),
    ('o1075', 'website/blog/index.html', 'before the actual run breaches the declared cap'),
    ('o1086', 'website/blog/index.html', 'cost-bounded execution proven by Z3'),
    ('o1087', 'website/blog/index.html', 'It proves three things:'),
    ('o1088', 'website/blog/index.html', '<span class="st">VERIFIED: 10 proven, 0 warnings, 0 errors</span>'),
    ('o1098', 'website/docs/index.html', 'VERIFIED: 10 proven, 0 warnings, 0 errors'),
)

CORRECTED: tuple[tuple[str, str, str], ...] = (
    ('o0062', 'README.md', "check a signed execution trace against the static proof's envelope (obligations recomputed from the trace by interval checks, a Decimal sum and Ed25519; no Z3)"),
    ('o0196', 'docs/ANNEX_IV_MAPPING.md', 'the certificate checks that the trace conforms, not that the trace faithfully records reality'),
    ('o0200', 'docs/ANNEX_IV_MAPPING.md', 'embedded in the manifest evidences that the artifact existed at the log timestamp'),
    ('o0204', 'docs/ANNEX_IV_MAPPING.md', '`verify_annex_iv_map.py` checks presence, authenticity, and indexing of the declared evidence (sha256 digests and an Ed25519 signature)'),
    ('o0209', 'docs/ATTESTATION_RECEIPT.md', 'what tee_attested evidences, and what it does not'),
    ('o0210', 'docs/ATTESTATION_RECEIPT.md', 'EVIDENCES (signature verification and count equality): the per-event token counts in a signed trace'),
    ('o0213', 'docs/ATTESTATION_RECEIPT.md', 'A TEE receipt evidences provenance and count-binding'),
    ('o0215', 'docs/ATTESTATION_RECEIPT.md', 'S146 verifies the mechanism and genuine-signature conformance (a published enclave receipt verifies through the production primitive)'),
    ('o0289+o0290', 'docs/COST_VERIFICATION_GUIDE.md', 'call is made, that the declared cost envelope stays under'),
    ('o0292', 'docs/COST_VERIFICATION_GUIDE.md', 'tie-in > "v5.0.0 ships'),
    ('o0356', 'docs/EU_AI_ACT_COMPLIANCE.md', 'Three declared legs are proven with Z3 before deployment: the cost cap, policy coverage and sequence ordering'),
    ('o0363', 'docs/GATED_ACTIONS.md', 'obligation #5 (authorization) checks, by Ed25519 verification, that every trace'),
    ('o0364', 'docs/GATED_ACTIONS.md', '## What this verifies, and what it does not'),
    ('o0365', 'docs/GATED_ACTIONS.md', '**Verifies (completeness of the gated set, by the `smt_spec_sha256` binding):**'),
    ('o0367', 'docs/GATED_ACTIONS.md', 'Obligation #5 verifies, by Ed25519 signature, that SOME key bound to the'),
    ('o0500', 'docs/RUNTIME_CONFORMANCE.md', 'a run can exceed what it declared, and the proof says nothing about any particular run'),
    ('o0501', 'docs/RUNTIME_CONFORMANCE.md', 'rather than counted as passing, so an auditor'),
    ('o0502', 'docs/RUNTIME_CONFORMANCE.md', 'The offline verifier checks, by Ed25519 signature and sha256 binding, that the signed verdict is authentic'),
    ('o0503', 'docs/RUNTIME_CONFORMANCE.md', 'The certificate checks that the **trace** conforms'),
    ('o0504', 'docs/RUNTIME_CONFORMANCE.md', '**What obligation #5 now verifies**'),
    ('o0506', 'docs/RUNTIME_CONFORMANCE.md', 'The verifier checks, by Ed25519 signature, that SOME key bound to the'),
    ('o0526', 'docs/SEQUENCE_LAWS.md', 'the DICE checks, against one signed trace, that a game was played by the rules'),
    ('o0527', 'docs/SEQUENCE_LAWS.md', 'proves `unsat` (no path the declarations allow exceeds the cap)'),
    ('o0530', 'docs/SEQUENCE_LAWS.md', 'The certificate checks that the trace conforms, not that the trace faithfully records reality.'),
    ('o0575', 'docs/VERIFY_DOSSIER.md', '| What you need | What it verifies |'),
    ('o0581', 'docs/WITNESSED_RUN_EVIDENCE.md', 'The compiled path records a cost ENVELOPE: the declared costs, which Z3 bounds by the declared cost cap on every path the declarations allow.'),
    ('o0582', 'docs/WITNESSED_RUN_EVIDENCE.md', 'VERIFIED (recomputation): obligation #4 recomputes the realized total'),
    ('o0583', 'docs/WITNESSED_RUN_EVIDENCE.md', 'the signature evidences that the ISSUER did not tamper'),
    ('o0805', 'trace/SPEC.md', 'The Verifier checks *consistency of record and verdict*, not sensor truth.'),
    ('o1116', 'website/index.html', 'NOUS proves the rules you declare hold on every path the declarations allow'),
    ('o1118', 'website/index.html', 'The system proves the declared rules hold on every path the declarations allow'),
    ('o1121', 'website/index.html', 'NOUS builds a mathematical region that proves the declared rules hold on every path the declarations allow'),
    ('o1123', 'website/index.html', 'the literature talks about: a mathematical region that proves the declared rules hold on every path the declarations allow'),
    ('o1130', 'website/index.html', '>A mathematical region that proves the declared rules hold on every path the declarations allow.<'),
    ('o1138', 'website/index.html', 'A formal envelope that proves the declared rules hold on every path the declarations allow.'),
    ('o1143', 'website/index.html', 'Before a run, Z3 proves the declared blocking net has no coverage gap, and NOUS records every decision for deterministic replay.'),
    ('o1147', 'website/lending.html', 'NOUS proves the policy has no coverage gap, and evidences the decision stayed in it.'),
    ('o1150', 'website/lending.html', '<h3>What you can verify</h3>'),
    ('D376-7-lending-trust', 'website/lending.html', 'offline, trusting only the pinned public keys, whose binding to a name is operator-asserted.'),
    ('o1154', 'website/runtime.html', 'the runtime resilience layer that produce the runs NOUS evidences.'),
    ('o0881', 'website/blog/index.html', '<h2 class="post-title">v5.66.0 &mdash; The Cost Cap Reaches the Dossier, On a Self-Attesting Path</h2>'),
    ('o0937', 'website/blog/index.html', '<h1>v5.66.0 &mdash; The Cost Cap Reaches the Dossier, On a Self-Attesting Path</h1>'),
    ('o0938', 'website/blog/index.html', '<strong>The self-attesting path.</strong>'),
    ('o0939', 'website/blog/index.html', 'The pipeline now attests its own provenance instead of merely asserting it.'),
    ('o0887', 'website/blog/index.html', 'plus the <strong>binding</strong> leg checking that the log-anchored digest equals'),
    ('o0899', 'website/blog/index.html', 'Mechanism and conformance verified; production pin pending a ceremony.'),
    ('o0900', 'website/blog/index.html', 'it evidences, by signature, that the issuer did not tamper with the relayed usage'),
    ('o0903', 'website/blog/index.html', 'It checks presence and indexing &mdash; NOT legal sufficiency.'),
    ('o0915', 'website/blog/index.html', 'The envelope-binding chain verified an unbroken lineage but said nothing'),
    ('o0919', 'website/blog/index.html', 'A certificate checks that one build stayed in its envelope.'),
    ('o0921', 'website/blog/index.html', 'laws separately from satisfied ones, and the static verifier warns'),
    ('o0952', 'website/blog/index.html', 'The digest whose inclusion Root 2 verifies is read from the same canonicalized log body'),
    ('o0962', 'website/blog/index.html', 'the conformance certificate checks that the run stayed inside the envelope,'),
    ('o0974', 'website/blog/index.html', 'the signature evidences authenticity, but the independent sha check is what catches the lie.'),
    ('o0982', 'website/blog/index.html', 'which verify each decision verb is cryptographically bound to its exact action and envelope.'),
    ('o0991', 'website/blog/index.html', 'transparency log, evidenced by a hashedrekord inclusion proof and a signed checkpoint,'),
    ('o0994', 'website/blog/index.html', 'A NOUS dossier&rsquo;s claims already verify offline: a signed manifest,'),
    ('o0997', 'website/blog/index.html', 'v5.45.0 verifies the mechanism and genuine-signature conformance;'),
    ('o0998+o0999', 'website/blog/index.html', 'asserts (verified by recomputation). The trace faithfully records what the runtime saw (assumed, but the signature evidences that the issuer did not tamper after the fact). And the provider'),
    ('o1000', 'website/blog/index.html', 'A receipt thus evidences provenance and count-binding:'),
    ('o1001+o1002', 'website/blog/index.html', 'asserts (verified by recomputation), the trace faithfully records what the runtime saw (assumed, but the signature evidences that the issuer did not tamper after the fact), and the provider'),
    ('o1005', 'website/blog/index.html', 'already proves two things offline: that the system&rsquo;s declared cost envelope stays inside its cap, and'),
    ('o1006', 'website/blog/index.html', 'This checks presence, authenticity, and indexing of the declared evidence'),
    ('o1031+o1032', 'website/blog/index.html', 'A conformance certificate checks that one build stayed inside its declared envelope. The v5.29.0 envelope-binding chain verified something across builds:'),
    ('o1039', 'website/blog/index.html', 'The through-line holds: NOUS evidences what it can sign and refuses the rest.'),
    ('o1045', 'website/blog/index.html', 'a run may <em>promote</em> a previously certified recovery,'),
    ('o1046', 'website/blog/index.html', '&mdash; to verify the run consulted exactly the memory state it claims.'),
    ('o1047', 'website/blog/index.html', 'a third party can verify a run trace existed at a point in time'),
    ('o1049', 'website/blog/index.html', 'and check that it conforms. The gap was upstream:'),
    ('o1050', 'website/blog/index.html', 'separately from genuinely satisfied ones.'),
    ('o1053', 'website/blog/index.html', 'And as with cost, the certificate checks that the <em>trace</em> conforms,'),
    ('o1054', 'website/blog/index.html', '<h2>What it verifies, and what it does not</h2>'),
    ('o1063', 'website/blog/index.html', '<code>proven</code> (no path the declarations allow exceeds the cap) or'),
    ('o1065', 'website/blog/index.html', 'A Z3 round-trip on EUR pricing checks that the architecture is currency-blind in fact, not just in claim.'),
    ('o1075', 'website/blog/index.html', 'before the declared envelope, re-priced, exceeds the cap.'),
    ('o1086', 'website/blog/index.html', 'a cost bound over the declared envelope proven by Z3, then'),
    ('o1087', 'website/blog/index.html', "Self-hosting isn't just a party trick. It is evidence of three things:"),
    ('o1088', 'website/blog/index.html', '<span class="st">VERIFIED: 10 checked, 0 warnings, 0 errors</span>'),
    ('o1098', 'website/docs/index.html', 'VERIFIED: 1 proven, 3 verified, 4 estimated, 0 reported, 0 warnings, 0 errors (9 checks)'),
    ('D376-1-adr0004', 'docs/adr/ADR-0004-proves-vs-evidences.md', 'S377 corrected the README, site, docs and blog copy that applied the verb to evidence (patch A)'),
)


def _text(rel: str) -> str:
    return _WS.sub(" ", (ROOT / rel).read_text(encoding="utf-8"))


@pytest.mark.parametrize("site,rel,phrase", OVERCLAIMS, ids=[r[0] for r in OVERCLAIMS])
def test_reserved_verb_overclaim_absent(site: str, rel: str, phrase: str) -> None:
    present: bool = phrase in _text(rel)
    assert present is False, f"{site}: overclaim still present in {rel}: {phrase!r}"


@pytest.mark.parametrize("site,rel,phrase", CORRECTED, ids=[r[0] for r in CORRECTED])
def test_corrected_copy_present(site: str, rel: str, phrase: str) -> None:
    present: bool = phrase in _text(rel)
    assert present is True, f"{site}: corrected copy missing in {rel}: {phrase!r}"
