#!/usr/bin/env python3
"""sync_grammar.py - regenerate grammar_data.py from nous.lark.

Single source of truth: nous.lark.
Generated artifact: grammar_data.py (Python module embedding the
grammar text, so flat-layout wheels can ship grammar without
data-file machinery).

Run before every build. Enforced by tests/test_grammar_sync.py.
"""
from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
GRAMMAR = ROOT / "nous.lark"
TARGET = ROOT / "grammar_data.py"

HEADER = (
    '"""Auto-generated by scripts/sync_grammar.py - DO NOT EDIT.\n\n'
    'Source of truth: nous.lark\n'
    '"""\n'
    'from __future__ import annotations\n\n'
)


def render(grammar_text: str) -> str:
    return (
        HEADER
        + '_GRAMMAR: str = ' + repr(grammar_text) + '\n\n\n'
        + 'def get_grammar() -> str:\n'
        + '    return _GRAMMAR\n'
    )


def main() -> int:
    if not GRAMMAR.exists():
        print(f"ERROR: {GRAMMAR} not found", file=sys.stderr)
        return 1
    grammar_text = GRAMMAR.read_text(encoding="utf-8")
    new_content = render(grammar_text)
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == new_content:
        print(f"OK: {TARGET.name} already in sync ({len(grammar_text)} chars)")
        return 0
    TARGET.write_text(new_content, encoding="utf-8")
    print(f"WROTE: {TARGET.name} ({len(grammar_text)} chars from nous.lark)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
